export interface BangHieuBillJoinCustomer {
    _id: string,
    idCustomer: string,
    note: string,
    width: number,
    height: number,
    amount: number,
    discount: number,
    totalPrice: number,
    billPrice: number,
    deposit: number,
    state: string,
    image: string,
    materialType: string,
    isTwoFace: boolean,
    toleNumber: number,
    hasFooter: boolean,
    isDelivery: boolean,
    costIncurred: number,
    createdAt: string,
    updatedAt: string,
    customerName?: string,
    phoneNumber?: string
}